name: Comment the diff of new commits

on:
  push:
    branches:
      - main

jobs:
  comment_diffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyGithub
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run Python script
        run: python src/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
